# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChooseUsers.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSql import QSqlQuery


class ChooseUsers_Dialog(object):
    def addUser(self, listItem):
        print(self.listWidget.currentItem().text(), self.users[self.listWidget.currentItem().text()])
        if self.users[self.listWidget.currentItem().text()] not in self.selected_users:
            self.selected_users.add(self.users[self.listWidget.currentItem().text()])
            t = QtWidgets.QListWidgetItem(self.listWidget_2)
            t.setText(self.listWidget.currentItem().text())


    def deleteUser(self, listItem):
        print(self.listWidget_2.currentItem().text(), self.users[self.listWidget_2.currentItem().text()])
        if self.users[self.listWidget_2.currentItem().text()] in self.selected_users:
            self.selected_users.remove(self.users[self.listWidget_2.currentItem().text()])
            self.listWidget_2.removeItemWidget(listItem)
            self.listWidget_2.takeItem(self.listWidget_2.row(listItem))

        print("USRS",self.selected_users)

    def fill_list(self):
        Users = QSqlQuery()
        Users.exec(
            """
            SELECT * FROM user
            """
        )
        self.users = {}
        while Users.next():
            self.users.update({Users.value(1) : Users.value(0)})
            t = QtWidgets.QListWidgetItem(self.listWidget)
            t.setText(Users.value(1))


    def setupUi(self, Dialog, mainwindow, connection):
        self.selected_users = set()
        self.mainwindow = mainwindow
        self.connection = connection

        Dialog.setObjectName("Dialog")
        Dialog.resize(484, 351)
        Dialog.setMinimumSize(QtCore.QSize(484, 351))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(390, 270, 81, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(20, 20, 171, 301))
        self.fill_list() # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        self.listWidget.itemDoubleClicked.connect(self.addUser)



        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setEnabled(True)
        self.listWidget_2.setGeometry(QtCore.QRect(200, 20, 171, 301))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_2.itemDoubleClicked.connect(self.deleteUser)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
