# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.ChooseUsers import ChooseUsers_Dialog


class Ui_Dialog(object):
    '''
    Класс, описывающий диалог параметров текстового отчёта

    Автор
    -----
    Илья Абрамов
    '''
    def openChooseUsers(self):
        '''
        Метод, запускающий окно выбора пользователей для отображения на графике

        Автор
        -----
        Илья Абрамов
        '''
        self.dialog.show()
        self.dialog.exec()
        if self.dialog.result() == 1:
            self.selected_users = self.ui.selected_users

    def setupUi(self, Dialog, mainwindow, connection):
        '''
        Метод инициализации интерфейса диалога выбора пользователей

        Автор
        -----
        Илья Абрамов, Яна Евдокимова
        '''
        self.connection = connection
        self.dialog = QtWidgets.QDialog()
        self.ui = ChooseUsers_Dialog()
        self.ui.setupUi(self.dialog, self,self.connection)
        self.selected_users = []

        self.mainwindow = mainwindow
        Dialog.setObjectName("Dialog")
        # Dialog.resize(480, 350)
        Dialog.setWindowIcon(QtGui.QIcon('ui/logo.png'))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dateEdit = QtWidgets.QDateTimeEdit(Dialog)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setDateTime(QtCore.QDateTime(2022, 3, 17, 0, 0, 0, 0))  # Базовое время
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setMinimumDate(QtCore.QDate(2022, 3, 16))
        self.dateEdit.setMaximumDate(QtCore.QDate(2022, 6, 1))
        self.verticalLayout.addWidget(self.dateEdit)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.dateEdit_2 = QtWidgets.QDateTimeEdit(Dialog)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_2.setDateTime(QtCore.QDateTime(2022, 3, 18, 0, 0, 0, 0))  # Базовое время
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setMinimumDate(QtCore.QDate(2022, 3, 16))
        self.dateEdit_2.setMaximumDate(QtCore.QDate(2022, 6, 1))
        self.verticalLayout.addWidget(self.dateEdit_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.openChooseUsers)
        self.verticalLayout.addWidget(self.pushButton)
        self.lineSpacer1 = QtWidgets.QFrame(Dialog)
        self.lineSpacer1.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineSpacer1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSpacer1.setObjectName("lineSpacer1")
        self.verticalLayout.addWidget(self.lineSpacer1)

        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)

        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)  # Dialog.reject
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def retranslateUi(self, Dialog):
        '''
        Метод добавления подписей к элементам интерфейса

        Автор
        -----
        Яна Евдокимова
        '''
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создание текстового отчёта"))
        self.radioButton_2.setText(_translate("Dialog", "Список сессий выбранных пользователей"))
        self.radioButton_3.setText(_translate("Dialog", "Активные пользователи"))
        self.radioButton.setText(_translate("Dialog", "Количество сессий выбранных пользователей с разбивкой по платформам (сводная таблица)"))
        self.label.setText(_translate("Dialog", "Укажите начало периода:"))
        self.label_2.setText(_translate("Dialog", "Укажите конец периода:"))
        self.label_3.setText(_translate("Dialog", "Выберите пользователей:"))
        self.pushButton.setText(_translate("Dialog", "Открыть таблицу"))
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setText(_translate("Dialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
